name: CI

on:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build mouse-selection
        run: ./mouse-selection/build.sh

      - name: Build battery
        run: ./battery/build.sh
